import { type InputDefinition, type OutputDefinition, type TypeDefinition } from "./registry";

//? Ports: what a program exposes to the outside, as DATA - the inputs it reads, the outputs it
// produces, and the struct types those need. A PortLayer is a named Ports bundle with a policy;
// layers stack (a host contract, a capability, the user's own declarations) and compose into the
// descriptor the analyser and runtime see (language/compose.ts). Pure and JSON-safe, so a layer
// can travel with a saved program. The policy says who may edit the declarations, who feeds the
// values at runtime, and whether the layer is saved with the program; core reads those fields,
// it never branches on a layer "kind" - the presets below are just the two common combinations.

/** A struct type a layer declares; compose supplies the schema. */
export type PortType = Omit<TypeDefinition, "schema">;

export interface Ports {
  readonly types?: readonly PortType[];
  readonly inputs: readonly InputDefinition[];
  readonly outputs: readonly OutputDefinition[];
}

export interface LayerPolicy {
  /** May a UI change this layer's declarations? */
  editable: boolean;
  /** Who supplies the values at runtime: host code, or a user typing them. */
  feeds: "host" | "user";
  /** Is the layer saved with the program (snapshots), or regenerated by the host? */
  persisted: boolean;
}

export interface PortLayer {
  id: string;
  ports: Ports;
  policy: LayerPolicy;
}

/** The two policies every host has, plus a builder for the rest (Strategy as data). */
export const Policy = Object.freeze({
  /** Made in code, not editable, host-fed, regenerated at mount. */
  host: Object.freeze<LayerPolicy>({ editable: false, feeds: "host", persisted: false }),
  /** The user's declarations: editable, user-fed, saved with the program. */
  user: Object.freeze<LayerPolicy>({ editable: true, feeds: "user", persisted: true }),
  custom: (base: LayerPolicy, overrides: Partial<LayerPolicy>): LayerPolicy =>
    Object.freeze({ ...base, ...overrides }),
});

export const EMPTY_PORTS: Ports = Object.freeze({
  inputs: Object.freeze([]),
  outputs: Object.freeze([]),
});

/** Concatenate layers in order into one Ports (types only when some layer declares any). */
export function flattenPorts(layers: readonly PortLayer[]): Ports {
  const types = layers.flatMap((layer) => layer.ports.types ?? []);
  return {
    ...(types.length > 0 ? { types } : {}),
    inputs: layers.flatMap((layer) => layer.ports.inputs),
    outputs: layers.flatMap((layer) => layer.ports.outputs),
  };
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

// A declaration is a record with a string name and a structured type ({ kind: ... }).
const isDeclaration = (value: unknown): boolean =>
  isRecord(value) &&
  typeof value["name"] === "string" &&
  isRecord(value["type"]) &&
  typeof value["type"]["kind"] === "string";

const isTypeDeclaration = (value: unknown): boolean =>
  isRecord(value) &&
  typeof value["name"] === "string" &&
  (value["fields"] === undefined || isRecord(value["fields"])) &&
  (value["extends"] === undefined || typeof value["extends"] === "string");

/** Structural guard for stored ports (a saved program's `ports`, a share URL). */
export function isPorts(value: unknown): value is Ports {
  if (!isRecord(value)) return false;
  const { types, inputs, outputs } = value;
  return (
    (types === undefined || (Array.isArray(types) && types.every(isTypeDeclaration))) &&
    Array.isArray(inputs) &&
    inputs.every(isDeclaration) &&
    Array.isArray(outputs) &&
    outputs.every(isDeclaration)
  );
}
